name: elite_card
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Vos nouveaux packages ajoutés ici avec le bon alignement :
  image_picker: ^1.0.7
  sensors_plus: ^6.0.0
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true